### ISSUE TITLE
Double-click to select word as in Notepad

### ISSUE THREAD

**Issue by medo64** [medo64/QText#11]
Plesse add double click in Text to select a word AS in notepad.

**Comment by smaragdus** [comment]
@medo64 

For me double click works as expected (selecting a single word). Yet you may add triple click to select a whole paragraph.

**Comment by medo64** [comment]
Triple click added in 'new' branch (QText rewrite to be multi-platform). Beta version available as [0.1.15](https://github.com/medo64/QText/releases/tag/v0.1.15)
